name: Fetch Reddit Posts Daily

on:
  schedule:
    - cron: "0 3 * * *" # Runs every day at 03:00 UTC
  workflow_dispatch:     # Also lets you run it manually

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install

      - name: Run fetch script
        run: pnpm tsx scripts/fetch-reddit.ts

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/data/reddit.json public/reddit/*
          git commit -m "🤖 Auto-update Reddit posts"
          git push
